name: ARB Production

on:
  push:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    name: Build production version of ARB
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: add tap from current branch
      run: |
        mkdir -p $(dirname $(brew --repo arb-project/arb))
        ln -s $PWD $(brew --repo arb-project/arb)
    - name: install X11 server
      run: brew install --cask xquartz
    - name: install other ARB dependencies
      run: brew install arb-project/arb/arb --only-dependencies
    - name: build ARB
      env:
        HOMEBREW_LOGS: .homebrew-logs
      run: brew install arb-project/arb/arb
    - name: save Homebrew logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Homebrew logs
        path: .homebrew-logs/
