name: ARB head with tests

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Run tests for head version of ARB
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: add tap from current branch
      run: |
        mkdir -p $(dirname $(brew --repo arb-project/arb))
        ln -s $PWD $(brew --repo arb-project/arb)
    - name: install X11 server
      run: brew install --cask xquartz
    - name: install other ARB dependencies
      run: brew install arb-project/arb/arb --HEAD --only-dependencies
    - name: build HEAD version of ARB
      env:
        HOMEBREW_LOGS: ${{github.workspace}}/.homebrew-logs
      run: brew install arb-project/arb/arb --HEAD --with-test-only --keep-tmp
    - name: save Homebrew logs
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: Homebrew logs
        path: .homebrew-logs/
