name: ARB head

on: [push]

jobs:
  build:

    runs-on: macos-latest
        
    steps:
    - name: add taps
      run: | 
        brew tap arb-project/arb
        brew tap denismm/gv
    - name: install X11 server
      run: brew cask install xquartz
    - name: install other ARB dependencies
      run: brew install arb --HEAD --only-dependencies
    - name: build HEAD version of ARB
      env:
        HOMEBREW_LOGS: .homebrew-logs
      run: brew install arb --HEAD --verbose
    - name: save Homebrew logs
      uses: actions/upload-artifact@v1
      with:
        name: Homebrew logs
        path: .homebrew-logs/
