name: ARB head with tests

on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Run tests for head version of ARB
    runs-on: macos-latest

    steps:
    - name: add taps
      run: |
        brew tap arb-project/arb
        brew tap denismm/gv
    - name: install X11 server
      run: brew cask install xquartz
    - name: install other ARB dependencies
      run: brew install arb --HEAD --only-dependencies
    - name: build HEAD version of ARB
      env:
        HOMEBREW_LOGS: .homebrew-logs
      run: brew install arb --HEAD --with-test-only --keep-tmp
    - name: save Homebrew logs
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: Homebrew logs
        path: .homebrew-logs/
